### ISSUE TITLE
open terminal failed: missing or unsuitable terminal: xterm-256color

### ISSUE THREAD

**Issue by commiyou** [romkatv/tmux-bin#1]
wsl2  ubuntu18.04 lts，`tmux` give the following error message:
```
open terminal failed: missing or unsuitable terminal: xterm-256color
```
run `TERM=screen-256color tmux` give the following error message
```
open terminal failed: missing or unsuitable terminal: screen-256color
```

**Comment by romkatv** [comment]
Why are you using this code? What do you expect to happen when you do?

**Comment by commiyou** [comment]
I'm using zinit with configs as follow to get a portable development environment
```
zinit ice lucid from"gh-r" as"program" pick'bin/tmux'
zinit load romkatv/tmux-bin
```

**Comment by romkatv** [comment]
This project is not packaging tmux. It’s packaging an incompatible fork. It’s unlikely that you want to use it.

**Comment by romkatv** [comment]
I've added a [readme](https://github.com/romkatv/tmux-bin/blob/master/README.md) to make the nature of this project clearer.
