### ISSUE TITLE
Compiling on ppc64

### ISSUE THREAD

**Issue by seanfarley** [romkatv/tmux-bin#2]
Similar to https://github.com/romkatv/gitstatus/issues/277, I'm trying to get my shell prompt working. Unfortunately, the build script seems to force docker which I can't install.

From the error message,

```
z4h: installing tmux
error: there is no prebuilt binary for your architecture

See https://github.com/romkatv/tmux-bin#compiling for building one.

z4h: init failed

See error messages above to identify the culprit.
```

There are no instructions for compiling from source. I'm not sure how to proceed.

**Comment by romkatv** [comment]
Check out https://github.com/romkatv/tmux-bin/blob/master/README.md. I don't have anything else to add.

**Comment by seanfarley** [comment]
Well, for starters, you shouldn't link to something that doesn't exist (`See https://github.com/romkatv/tmux-bin#compiling`). I guess that went over your head. The patch should be almost identical to the one linked but I couldn't run it to test it. With `gitstatusd` built I'm down to only this error for having `zsh4humans` working.

**Comment by romkatv** [comment]
> Well, for starters, you shouldn't link to something that doesn't exist (`See https://github.com/romkatv/tmux-bin#compiling`). I guess that went over your head.

What have I linked to that doesn't exist?

**Comment by romkatv** [comment]
> What have I linked to that doesn't exist?

I see what you mean. You've bypassed the architecture check though, so anything goes there.

**Comment by seanfarley** [comment]
> > What have I linked to that doesn't exist?
> 
> I see what you mean. You've bypassed the architecture check though, so anything goes there.

As a (newish) user, I have no idea how or what this means. I copied over my zsh settings and z4h started to download things and install itself which lead to the `tmux` error message I posted above.

**Comment by romkatv** [comment]
If you try to install zsh4humans (via the installer) on ppc64, it'll tell you the architecture is unsupported. If you try to SSH teleport to a ppc64 machine, it'll give you plain SSH. But if you install zsh4humans on one machine and manually copy it to another, it won't perform the architecture check and you'll get weird errors.

I thought you intentionally did that, hence I said "bypassed". If this was not intentional, I apologize. I'll add an extra check when zsh is booting up.

**Comment by romkatv** [comment]
> I'll add an extra check when zsh is booting up.

This is done.
